# Generated by Django 5.0.1 on 2025-10-23 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_flow', to='documents.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('current_max_order_approved', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='validation.validationflow')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('step_order', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='validation.validationinstance')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['instance', 'created_at'], name='validation__instanc_85a698_idx'), models.Index(fields=['actor_user_id'], name='validation__actor_u_8f6dbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('approver_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='validation.validationflow')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['flow', 'order'], name='validation__flow_id_f43c38_idx'), models.Index(fields=['approver_user_id'], name='validation__approve_bd345d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='validationstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='unique_flow_order'),
        ),
    ]
