# Generated by Django 5.0.1 on 2025-10-23 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('bucket_key', models.CharField(max_length=500)),
                ('bucket_provider', models.CharField(choices=[('S3', 'Amazon S3'), ('GCS', 'Google Cloud Storage')], max_length=10)),
                ('hash_hex', models.CharField(blank=True, max_length=128, null=True)),
                ('validation_status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_audits', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStateAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, max_length=1, null=True)),
                ('to_status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_state_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_audits', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'entity_type', 'entity_id'], name='documents_d_company_282003_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['validation_status'], name='documents_d_validat_bbb925_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('company', 'bucket_key'), name='unique_company_bucket_key'),
        ),
        migrations.AddIndex(
            model_name='documentdownloadaudit',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_2a9629_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstateaudit',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_05aff3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstateaudit',
            index=models.Index(fields=['action'], name='documents_d_action_30489b_idx'),
        ),
    ]
